# Generated by Django 5.0.6 on 2025-01-16 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('courses', models.ManyToManyField(to='courses.course')),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='students_st_email_e271bc_idx')],
            },
        ),
    ]
