# Generated by Django 5.0.6 on 2025-01-16 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='courses_cou_code_612388_idx')],
            },
        ),
    ]
